Migrated RC1 content from Confluence
chef/chef-client-docs pull request #6
Opened 2024-11-25 14:42 UTC by lbarry316

## Description

I migrated the content from here - https://progresssoftware.atlassian.net/wiki/spaces/Infra19/pages/1212613103/RC1+Documentation - to the markdown toolstack. I also made editorial and formatting improvements.

## Version

These are changes for Chef Infra Client version(s):

- [x] RC1
- [ ] RC2
- [ ] version 19

## Definition of done

## Issues resolved

## Related PRs

## Checklist

- [ ] spellcheck
- [ ] use [relref shortcode](https://gohugo.io/content-management/cross-references/#use-of-ref-and-relref) for links to Client docs in this doc set
- [ ] all tests pass

2024-11-26 16:42 UTC, Vasu1105 commented on content/kitchen/_index.md
> +hab pkg install chef/test-kitchen/3.7.1
```suggestion
[hab pkg install chef/test-kitchen/3.7.1](https://hub.docker.com/r/chef/chef-hab/tags)
```

2024-11-26 16:43 UTC, Vasu1105 commented on content/kitchen/_index.md
> +hab pkg install chef/test-kitchen/3.7.1
```suggestion
sudo hab pkg install --binlink --force chef/chef-test-kitchen-enterprise
```

2024-11-26 16:44 UTC, Vasu1105 commented on content/kitchen/_index.md
> +hab pkg install chef/test-kitchen/3.7.1
This needs needs to be updated since user will be installing new chef-test-kitchen-enterprise

2024-11-26 16:53 UTC, Vasu1105 requested changes

2024-11-26 16:53 UTC, Vasu1105 commented on content/kitchen/using_test_kitchen.md
> +  privileged: true
```suggestion
  privileged: true
  chef_version: unstable
```

2024-11-26 16:55 UTC, Vasu1105 commented on content/kitchen/using_test_kitchen.md
> +  privileged: true
User has to specify chef_version as unstable to pull latest Chef Infra 19 image for RC1 cc @brianLoomis

2024-11-27 14:04 UTC, IanMadd approved these changes

2024-11-27 14:04 UTC, merged